services:
  - type: web
    name: cozia-product-research
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
